
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(469, 442)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 410, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 0, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 50, 78, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 50, 291, 341))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.month_1_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_1_usage.setObjectName("month_1_usage")
        self.verticalLayout_2.addWidget(self.month_1_usage)
        self.month_2_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_2_usage.setObjectName("month_2_usage")
        self.verticalLayout_2.addWidget(self.month_2_usage)
        self.month_3_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_3_usage.setObjectName("month_3_usage")
        self.verticalLayout_2.addWidget(self.month_3_usage)
        self.month_4_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_4_usage.setObjectName("month_4_usage")
        self.verticalLayout_2.addWidget(self.month_4_usage)
        self.month_5_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_5_usage.setObjectName("month_5_usage")
        self.verticalLayout_2.addWidget(self.month_5_usage)
        self.month_6_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_6_usage.setObjectName("month_6_usage")
        self.verticalLayout_2.addWidget(self.month_6_usage)
        self.month_7_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_7_usage.setObjectName("month_7_usage")
        self.verticalLayout_2.addWidget(self.month_7_usage)
        self.month_8_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_8_usage.setObjectName("month_8_usage")
        self.verticalLayout_2.addWidget(self.month_8_usage)
        self.month_9_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_9_usage.setObjectName("month_9_usage")
        self.verticalLayout_2.addWidget(self.month_9_usage)
        self.month_10_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_10_usage.setObjectName("month_10_usage")
        self.verticalLayout_2.addWidget(self.month_10_usage)
        self.month_11_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_11_usage.setObjectName("month_11_usage")
        self.verticalLayout_2.addWidget(self.month_11_usage)
        self.month_12_usage = QtWidgets.QDoubleSpinBox(self.layoutWidget1,maximum=100000000000000000,minimum=0)
        self.month_12_usage.setObjectName("month_12_usage")
        self.verticalLayout_2.addWidget(self.month_12_usage)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "monthly_usage"))
        self.label.setText(_translate("Dialog", "Monthly usage"))
        self.label_4.setText(_translate("Dialog", "Month 1"))
        self.label_3.setText(_translate("Dialog", "Month 2"))
        self.label_2.setText(_translate("Dialog", "Month 3"))
        self.label_6.setText(_translate("Dialog", "Month 4"))
        self.label_5.setText(_translate("Dialog", "Month 5"))
        self.label_11.setText(_translate("Dialog", "Month 6"))
        self.label_7.setText(_translate("Dialog", "Month 7"))
        self.label_8.setText(_translate("Dialog", "Month 8"))
        self.label_12.setText(_translate("Dialog", "Month 9"))
        self.label_9.setText(_translate("Dialog", "Month 10"))
        self.label_10.setText(_translate("Dialog", "Month 11"))
        self.label_13.setText(_translate("Dialog", "Month 12"))
