from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(515, 427)
        self.password_text = QtWidgets.QLineEdit(Dialog)
        self.password_text.setGeometry(QtCore.QRect(140, 320, 294, 31))
        self.password_text.setObjectName("password_text")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 280, 291, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(100, 40, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 200, 61, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.job = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.job.setFont(font)
        self.job.setAlignment(QtCore.Qt.AlignCenter)
        self.job.setObjectName("job")
        self.horizontalLayout_3.addWidget(self.job)
        self.salary_text = QtWidgets.QComboBox(Dialog)
        self.salary_text.setGeometry(QtCore.QRect(140, 240, 291, 31))
        self.salary_text.setObjectName("salary_text")
        self.salary_text.addItem("Daily wage")
        self.salary_text.addItem("Weekly wage")
        self.salary_text.addItem("Monthly wage")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(60, 120, 81, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 320, 101, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.password = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.horizontalLayout_6.addWidget(self.password)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(100, 160, 41, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.age = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.age.setFont(font)
        self.age.setAlignment(QtCore.Qt.AlignCenter)
        self.age.setObjectName("age")
        self.horizontalLayout_2.addWidget(self.age)
        self.continue_2 = QtWidgets.QPushButton(Dialog)
        self.continue_2.setGeometry(QtCore.QRect(340, 380, 121, 31))
        self.continue_2.setObjectName("continue_2")
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(70, 240, 71, 31))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.salary = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.salary.setFont(font)
        self.salary.setAlignment(QtCore.Qt.AlignCenter)
        self.salary.setObjectName("salary")
        self.horizontalLayout_4.addWidget(self.salary)
        self.layoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(70, 280, 71, 31))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.age_text = QtWidgets.QSpinBox(Dialog)
        self.age_text.setGeometry(QtCore.QRect(140, 160, 291, 31))
        self.age_text.setObjectName("age_text")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 461, 16))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.name_text = QtWidgets.QLineEdit(Dialog)
        self.name_text.setGeometry(QtCore.QRect(140, 120, 291, 31))
        self.name_text.setObjectName("name_text")
        self.job_text = QtWidgets.QLineEdit(Dialog)
        self.job_text.setGeometry(QtCore.QRect(140, 200, 292, 31))
        self.job_text.setObjectName("job_text")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "PROFIT OR LOSE"))
        self.job.setText(_translate("Dialog", "JOB"))
        self.name.setText(_translate("Dialog", "NAME"))
        self.password.setText(_translate("Dialog", "PASSWORD"))
        self.age.setText(_translate("Dialog", "AGE"))
        self.continue_2.setText(_translate("Dialog", "Continue"))
        self.salary.setText(_translate("Dialog", "SALARY"))
        self.label.setText(_translate("Dialog", "Gmail"))
        self.label_6.setText(_translate("Dialog", "FILL ALL THE INFORMATION CORRECTLY AND GO TO NEXT STEP"))
